[package]
name = "WBA-Q125-prereq2"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.15.2"
solana-sdk = "1.15.2"
bs58 = "0.4"
solana-client = "1.15.2"

[lib]
path = "src/lib.rs"
